//all type of smartphone in the store
const smartphones_arr = [
  {
    image: "Smartphone/s_a35.jpg",
    logo: "Smartphone/logo_Samsung.jpg",
    name: "Galaxy",
    type: "A35",
    company: "Samsung",
    color: "Black",
    details:
      "Samsung Galaxy A35 5G 8GB+256GB - Awesome Iceblue - 2 Year Warranty",
    price: "₪3,645",
  },
  {
    image: "Smartphone/a_15.jpg",
    logo: "Smartphone/logo_apple.jpg",
    name: "iPhone",
    type: "15",
    company: "Apple",
    color: "White",
    details:
      "Apple iPhone 15 256GB - Black - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪4,949",
  },
  {
    image: "Smartphone/x_a3.jpg",
    logo: "Smartphone/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "A3",
    company: "Xiaomi",
    color: "Black",
    details:
      "Xiaomi Redmi A3 4GB+128GB Forest Green - 2 Years Warranty by Hemilton",
    price: "₪389",
  },
  {
    image: "Smartphone/s_s21_fe.jpg",
    logo: "Smartphone/logo_Samsung.jpg",
    name: "Galaxy",
    type: "S21 FE",
    company: "Samsung",
    color: "White",
    details:
      "Samsung Galaxy S21 FE 5G 8GB+256GB Graphite SM-G990B2/DS - 2 Year Warranty",
    price: "₪1,490",
  },
  {
    image: "Smartphone/a_15_pro _max.jpg",
    logo: "Smartphone/logo_apple.jpg",
    name: "iPhone",
    type: "15 Pro Max",
    company: "Apple",
    color: "Black",
    details:
      "Apple iPhone 15 Pro Max 256GB - Black Titanium - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪5,429",
  },
  {
    image: "Smartphone/s_s24_ultra.jpg",
    logo: "Smartphone/logo_Samsung.jpg",
    name: "Galaxy",
    type: "S24 Ultra",
    company: "Samsung",
    color: "White",
    details:
      "Samsung Galaxy S24 Ultra 12GB+256GB Titanium Gray (SM-S928B/DS) - 1 Year Official",
    price: "₪4,649",
  },
  {
    image: "Smartphone/x_13_pro+.jpg",
    logo: "Smartphone/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "Note 13 pro+",
    company: "Xiaomi",
    color: "Black",
    details:
      "Xiaomi Redmi Note 13 Pro+ 5G 12GB+512GB Aurora Purple - 2 Years Warranty by Hemilton",
    price: "₪1,720",
  },
  {
    image: "Smartphone/a_14_plus.jpg",
    logo: "Smartphone/logo_apple.jpg",
    name: "iPhone",
    type: "14 Plus",
    company: "Apple",
    color: "White",
    details:
      "Apple iPhone 14 Plus 128GB - Blue - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪2,899",
  },
  {
    image: "Smartphone/a_13.jpg",
    logo: "Smartphone/logo_apple.jpg",
    name: "iPhone",
    type: "13",
    company: "Apple",
    color: "Black",
    details:
      "Apple iPhone 13 128GB Starlight - 1 Year Warranty by The Official Distributor - Without Charger And Without Headphones",
    price: "₪2,499",
  },
  {
    image: "Smartphone/a_14_plus.jpg",
    name: "Galaxy",
    logo: "Smartphone/logo_Samsung.jpg",
    type: "Note 20 Ultra",
    company: "Samsung",
    color: "Black",
    details: "Samsung -  Galaxy Note20 Ultra 5G 128GB  - Mystic Black",
    price: "₪4,649",
  },
  {
    image: "Smartphone/x_12.jpg",
    logo: "Smartphone/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "12",
    company: "Xiaomi",
    color: "Black",
    details: "Xiaomi Redmi 12 4GB+128GB - Midnight Black",
    price: "₪559",
  },
  {
    image: "Smartphone/x_paco_m6.jpg",
    logo: "Smartphone/logo_Xiaomi.jpg",
    name: "Poco",
    type: "M6",
    company: "Xiaomi",
    color: "Black",
    details: "Xiaomi Poco M6 6GB+128GB Purple - 2 Years Warranty by Hemilton",
    price: "₪699",
  },
];

//all type of computers in the store
const computer_arr = [
  {
    image: "Computers/a_air_13.jpg",
    logo: "Computers/logo_apple.jpg",
    name: "MacBook",
    type: "air 13 M2",
    company: "Apple",
    color: "Midnight",
    details:
      "Apple - MacBook Air 13.6 Laptop - M2 chip Built for Apple Intelligence - 8GB Memory - 256GB SSD - Midnight",
    price: "₪5,429",
  },

  {
    image: "Computers/a_pro_14.jpg ",
    logo: "Computers/logo_apple.jpg",
    name: "MacBook",
    type: "pro 14 M3",
    company: "Apple",
    color: "space gray",
    details:
      "Apple - MacBook Pro 14 Laptop - M3 chip Built for Apple Intelligence - 8GB Memory - 10-core GPU - 1TB SSD - Space Gray",
    price: "₪5,429",
  },

  {
    image: "Computers/a_pro_16.jpg ",
    logo: "Computers/logo_apple.jpg",
    name: "MacBook",
    type: "pro 16 M3",
    company: "Apple",
    color: "Space Black",
    details:
      "Apple - MacBook Pro 16 Laptop - M3 Max chip Built for Apple Intelligence - 48GB Memory - 40-core GPU - 1TB SSD - Space Black",
    price: "₪5,429",
  },

  {
    image: "Computers/a_air_15.jpg",
    logo: "Computers/logo_apple.jpg",
    name: "MacBook",
    type: "air 15 M2",
    company: "Apple",
    color: "Starlight",
    details:
      " Apple - MacBook Air 15 Laptop - M2 chip Built for Apple Intelligence - 8GB Memory - 256GB SSD - Starlight",
    price: "₪5,429",
  },

  {
    image: "Computers/l_yoga_slim_x7.jpg",
    logo: "Computers/logo_lenovo.jpg",
    name: "Yoga",
    type: "Slim 7x",
    company: "Lenovo",
    color: "Cosmic Blue",
    details:
      "Lenovo - Yoga Slim 7x - Copilot+ PC - 14.5 3K OLED Touch-Screen Laptop - Snapdragon X Elite - 16GB Memory - 512GB SSD - Cosmic Blue",
    price: "₪5,429",
  },
  {
    image: "Computers/l_ideapad_1.jpg",
    logo: "Computers/logo_lenovo.jpg",
    name: "Ideapad",
    type: "Ideapad 1 ",
    company: "Lenovo",
    color: "Cloud Gray",
    details:
      "Lenovo - Ideapad 1 15.6 Full HD Touchscreen Laptop - Ryzen 7 5700U with 16GB Memory - AMD Radeon Graphics - 512GB SSD - Cloud Gray",
    price: "₪5,429",
  },
  {
    image: "Computers/l_Legion_Pro.jpg",
    logo: "Computers/logo_lenovo.jpg",
    name: "Legion ",
    type: "Pro 5i",
    company: "Lenovo",
    color: "Onyx Grey",
    details:
      "Lenovo - Legion Pro 5i 16 Gaming Laptop WQXGA - Intel 14th Gen Core i9 with 32GB Memory - NVIDIA GeForce RTX 4070 8GB - 2TB SSD - Onyx Grey",
    price: "₪5,429",
  },
  {
    image: "Computers/l_LOQ.jpg",
    logo: "Computers/logo_lenovo.jpg",
    name: " LOQ ",
    type: "LOQ 15.6 Gaming",
    company: "Lenovo",
    color: "Luna Grey",
    details:
      "Lenovo - LOQ 15.6 Gaming Laptop FHD - AMD Ryzen 7 7435HS with 16GB Memory - NVIDIA GeForce RTX 4060 8GB - 512GB SSD - Luna Grey",
    price: "₪5,429",
  },

  {
    image: "Computers/d_xps_13.jpg",
    logo: "Computers/logo_dell.jpg",
    name: "XPS 13 ",
    type: "13",
    company: "Dell",
    color: " Graphite",
    details:
      "Dell - XPS 13 - Copilot+ PC - 13.4 OLED Touch-Screen Laptop - Snapdragon X Elite w/ Dual Core Boost - 16GB Memory - 512GB SSD - Graphite",
    price: "₪5,429",
  },
  {
    image: "Computers/d_Inspiron.jpg",
    logo: "Computers/logo_dell.jpg",
    name: "Inspiron ",
    type: "Inspiron 16 2-in-1",
    company: "Dell",
    color: "Midnight Blue",
    details:
      "Dell - Inspiron 16 2-in-1 Mini-LED Touch Laptop Intel Core Ultra 7 Processor - 32GB Memory – 1TB SDD - Intel Arc Graphics - Midnight Blue",
    price: "₪5,429",
  },

  {
    image: "Computers/h_OmniBook.jpg",
    logo: "Computers/logo_hp.jpg",
    name: "OmniBook ",
    type: "OmniBook X",
    company: "HP",
    color: " Meteor Silver",
    details:
      "HP - OmniBook X - Copilot+ PC - 14 2.2K Touch-Screen Laptop - Snapdragon X Elite - 16GB Memory - 1TB SDD - Meteor Silver",
    price: "₪5,429",
  },
  {
    image: "Computers/h_Spectre.jpg",
    logo: "Computers/logo_hp.jpg",
    name: " Spectre ",
    type: "Spectre 2-in-1",
    company: "HP",
    color: "Nightfall Black",
    details:
      "HP - Spectre 2-in-1 14 2.8K OLED Touch-Screen Laptop - Intel Core Ultra 7 - Intel Evo Edition - 16GB Memory - 1TB SSD - Nightfall Black",
    price: "₪5,429",
  },
];

const props_arr = [
  {
    image: "props/protector.jpg",
    logo: "Smartphone/logo_Samsung.jpg",
    name: "Galaxy",
    type: "A35",
    company: "Samsung",
    color: "Black",
    details: "",
    price: "₪3,645",
  },
  {
    image: "props/a_15.jpg",
    logo: "props/logo_apple.jpg",
    name: "iPhone",
    type: "15",
    company: "Apple",
    color: "White",
    details:
      "Apple iPhone 15 256GB - Black - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪4,949",
  },
  {
    image: "props/x_a3.jpg",
    logo: "props/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "A3",
    company: "Xiaomi",
    color: "Black",
    details: "",
    price: "₪389",
  },
  {
    image: "props/s_s21_fe.jpg",
    logo: "props/logo_Samsung.jpg",
    name: "Galaxy",
    type: "S21 FE",
    company: "Samsung",
    color: "White",
    details: "",
    price: "₪1,490",
  },
  {
    image: "props/a_15_pro _max.jpg",
    logo: "props/logo_apple.jpg",
    name: "iPhone",
    type: "15 Pro Max",
    company: "Apple",
    color: "Black",
    details:
      "Apple iPhone 15 Pro Max 256GB - Black Titanium - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪5,429",
  },
  {
    image: "props/s_s24_ultra.jpg",
    logo: "props/logo_Samsung.jpg",
    name: "Galaxy",
    type: "S24 Ultra",
    company: "Samsung",
    color: "White",
    details: "",
    price: "₪4,649",
  },
  {
    image: "props/x_13_pro+.jpg",
    logo: "props/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "Note 13 pro+",
    company: "Xiaomi",
    color: "Black",
    details: "",
    price: "₪1,720",
  },
  {
    image: "props/a_14_plus.jpg",
    logo: "props/logo_apple.jpg",
    name: "iPhone",
    type: "14 Plus",
    company: "Apple",
    color: "White",
    details:
      "Apple iPhone 14 Plus 128GB - Blue - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪2,899",
  },
  {
    image: "props/a_13.jpg",
    logo: "props/logo_apple.jpg",
    name: "iPhone",
    type: "13",
    company: "Apple",
    color: "Black",
    details:
      "Apple iPhone 13 128GB Starlight - 1 Year Warranty by The Official Distributor - Without Charger And Without Headphones",
    price: "₪2,499",
  },
  {
    image: "props/a_14_plus.jpg",
    logo: "props/logo_Samsung.jpg",
    name: "Galaxy",
    type: "Note 20 Ultra",
    company: "Samsung",
    color: "Black",
    details: "",
    price: "₪4,649",
  },
  {
    image: "props/x_12.jpg",
    logo: "props/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "12",
    company: "Xiaomi",
    color: "Black",
    details: "",
    price: "₪559",
  },
  {
    image: "props/x_paco_m6.jpg",
    logo: "props/logo_Xiaomi.jpg",
    name: "Poco",
    type: "M6",
    company: "Xiaomi",
    color: "Black",
    details: "",
    price: "₪699",
  },
];
