//all type of smartphone in the store
const smartphones_arr = [
  {
    image: "Smartphone/s_a35.jpg",
    logo: "Smartphone/logo_Samsung.jpg",
    name: "Galaxy",
    type: "A35",
    company: "Samsung",
    color: "Black",
    details:
      "Samsung Galaxy A35 5G 8GB+256GB - Awesome Iceblue - 2 Year Warranty",
    price: "₪3,645",
  },
  {
    image: "Smartphone/a_15.jpg",
    logo: "Smartphone/logo_apple.jpg",
    name: "iPhone",
    type: "15",
    company: "Apple",
    color: "White",
    details:
      "Apple iPhone 15 256GB - Black - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪4,949",
  },
  {
    image: "Smartphone/x_a3.jpg",
    logo: "Smartphone/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "A3",
    company: "Xiaomi",
    color: "Green",
    details:
      "Xiaomi Redmi A3 4GB+128GB Forest Green - 2 Years Warranty by Hemilton",
    price: "₪389",
  },
  {
    image: "Smartphone/s_s21_fe.jpg",
    logo: "Smartphone/logo_Samsung.jpg",
    name: "Galaxy",
    type: "S21 FE",
    company: "Samsung",
    color: "Silver",
    details:
      "Samsung Galaxy S21 FE 5G 8GB+256GB Graphite SM-G990B2/DS - 2 Year Warranty",
    price: "₪1,490",
  },
  {
    image: "Smartphone/a_15_pro _max.jpg",
    logo: "Smartphone/logo_apple.jpg",
    name: "iPhone",
    type: "15 Pro Max",
    company: "Apple",
    color: "Silver",
    details:
      "Apple iPhone 15 Pro Max 256GB - Black Titanium - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪5,429",
  },
  {
    image: "Smartphone/s_s24_ultra.jpg",
    logo: "Smartphone/logo_Samsung.jpg",
    name: "Galaxy",
    type: "S24 Ultra",
    company: "Samsung",
    color: "White",
    details:
      "Samsung Galaxy S24 Ultra 12GB+256GB Titanium Gray (SM-S928B/DS) - 1 Year Official",
    price: "₪4,649",
  },
  {
    image: "Smartphone/x_13_pro+.jpg",
    logo: "Smartphone/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "Note 13 pro+",
    company: "Xiaomi",
    color: "Black",
    details:
      "Xiaomi Redmi Note 13 Pro+ 5G 12GB+512GB Aurora Purple - 2 Years Warranty by Hemilton",
    price: "₪1,720",
  },
  {
    image: "Smartphone/a_14_plus.jpg",
    logo: "Smartphone/logo_apple.jpg",
    name: "iPhone",
    type: "14 Plus",
    company: "Apple",
    color: "Red",
    details:
      "Apple iPhone 14 Plus 128GB - Blue - 1 Year Warranty by the Official Distributor - Without Charger and Without Headphones",
    price: "₪2,899",
  },
  {
    image: "Smartphone/a_13.jpg",
    logo: "Smartphone/logo_apple.jpg",
    name: "iPhone",
    type: "13",
    company: "Apple",
    color: "Black",
    details:
      "Apple iPhone 13 128GB Starlight - 1 Year Warranty by The Official Distributor - Without Charger And Without Headphones",
    price: "₪2,499",
  },
  {
    image: "Smartphone/s_note_20.jpg",
    name: "Galaxy",
    logo: "Smartphone/logo_Samsung.jpg",
    type: "Note 20 Ultra",
    company: "Samsung",
    color: "Black",
    details: "Samsung -  Galaxy Note20 Ultra 5G 128GB  - Mystic Black",
    price: "₪4,649",
  },
  {
    image: "Smartphone/x_12.jpg",
    logo: "Smartphone/logo_Xiaomi.jpg",
    name: "Redmi",
    type: "12",
    company: "Xiaomi",
    color: "Black",
    details: "Xiaomi Redmi 12 4GB+128GB - Midnight Black",
    price: "₪559",
  },
  {
    image: "Smartphone/x_paco_m6.jpg",
    logo: "Smartphone/logo_Xiaomi.jpg",
    name: "Poco",
    type: "M6",
    company: "Xiaomi",
    color: "White",
    details: "Xiaomi Poco M6 6GB+128GB Purple - 2 Years Warranty by Hemilton",
    price: "₪699",
  },
];

const props_arr = [
  {
    image: "props/AirPodsMax.jpg",
    logo: "props/",
    name: "AirPods ",
    type: "AirPods Max",
    company: "Apple",
    color: "Pink",
    details: "Apple - AirPods Max - Pink",
    price: "₪2,500",
  },
  {
    image: "props/sony2.jpg",
    logo: "props/",
    name: "QuietComfort",
    type: "QuietComfort",
    company: "Bose",
    color: "Black",
    details:
      "Bose - QuietComfort Wireless Noise Cancelling Over-the-Ear Headphones - Black",
    price: "₪899",
  },
  {
    image: "props/sony1.jpg",
    logo: "props/",
    name: "",
    type: "WH1000XM4",
    company: "Sony",
    color: "Black",
    details:
      "Sony - WH1000XM4 Wireless Noise-Cancelling Over-the-Ear Headphones - Black",
    price: "₪1199",
  },
  {
    image: "props/AirPodsPro2.jpg",
    logo: "props/",
    name: "",
    type: "",
    company: "Apple",
    color: "White",
    details: "Apple - AirPods Pro 2 - White",
    price: "₪1100",
  },
  {
    image: "props/mouse1.jpg",
    logo: "props/",
    name: "",
    type: "MX Master 3S",
    company: "Logitech",
    color: "Black",
    details:
      "Logitech - MX Master 3S Wireless Laser Mouse with Ultrafast Scrolling - Black",
    price: "₪169",
  },
  {
    image: "props/mouse2.jpg",
    logo: "props/",
    name: "",
    type: "",
    company: "Apple",
    color: "White",
    details: "Apple - Magic Mouse - White",
    price: "₪299",
  },
  {
    image: "props/mouse3.jpg",
    logo: "props/",
    name: "",
    type: "",
    company: "Razer",
    color: "Black",
    details:
      "Razer Basilisk V3 X HyperSpeed Customizable Wireless Gaming Mouse - Black",
    price: "₪120",
  },
  {
    image: "props/keyboard3.jpg",
    logo: "props/",
    name: "",
    type: " MX Keys S",
    company: "Logitech",
    color: "Black",
    details:
      "Logitech - MX Keys S Advanced Full-size Wireless Scissor Keyboard for PC and Mac with Backlit keys - Black",
    price: "₪199",
  },
  {
    image: "props/Keyboard2.jpg",
    logo: "props/",
    name: "",
    type: "MX Mechanical",
    company: "Logitech",
    color: "Graphite",
    details:
      "Logitech - MX Mechanical Full size Wireless Mechanical Tactile Switch Keyboard for Windows/macOS with Backlit Keys - Graphite",
    price: "₪239",
  },
  {
    image: "props/Keyboard1.jpg",
    logo: "props/",
    name: "",
    type: "Magic Keyboard",
    company: "Apple",
    color: "Silver/White",
    details:
      "Apple - Magic Keyboard full size with Numeric Keypad - Silver/White",
    price: "₪369",
  },
  {
    image: "props/WirelessChargingPad.jpg",
    logo: "props/",
    name: "",
    type: "Wireless Charging Pad",
    company: "Belkin",
    color: "Black",
    details:
      "Belkin - MagSafe 3-in-1 Wireless Charging Pad - Fast Wireless Charging for Apple Watch, iPhone 15, 14, 13 & 12 series, & AirPods - Black",
    price: "₪350",
  },
  {
    image: "props/Apple_Power_Adapter.jpg",
    logo: "props/",
    name: "",
    type: "12W USB ",
    company: "Apple",
    color: "White",
    details: "Apple - 12W USB Power Adapter - White",
    price: "₪94",
  },
  {
    image: "props/Anker735.jpg",
    logo: "props/",
    name: "",
    type: "735 65W ",
    company: "Anker",
    color: "Black",
    details:
      "Anker - 735 65W 3 Port USB Foldable Fast Wall Charger with GaN for iPhone/Samsung/Tablets/Laptops - Black",
    price: "₪125",
  },
  {
    image: "props/Cable.jpg",
    logo: "props/",
    name: "",
    type: "-Lightning Charging Cable ",
    company: "Apple",
    color: "White",
    details: "Apple - 6.6' (2M) USB Type C-to-Lightning Charging Cable - White",
    price: "₪69",
  },
];
